<?php

use App\Rol;
use Illuminate\Support\Facades\Config;

abstract class TestCase extends Illuminate\Foundation\Testing\TestCase
{
    /**
     * The base URL to use while testing the application.
     *
     * @var string
     */
    protected $baseUrl = 'http://localhost';

    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__ . '/../bootstrap/app.php';

        $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

        return $app;
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createRoles();
    }

    /**
     * @return void
     */
    private function createRoles(): void
    {
        foreach (Config::get('constants') as $key => $value) {
            factory(Rol::class)->create([
                'id' => $value,
            ]);
        }
    }
}
